sudo: false

language: node_js

node_js:
  - 4
  - 5
  - 0.10
  - 0.12

env:
  global:
    - AWS_ACCESS_KEY_ID=AKID
    - AWS_SECRET_ACCESS_KEY=SECRET
    - AWS_REGION=us-east-1
before_script:
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &
  - sleep 2
addons:
  hosts:
    - dynamodb-local
